apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:V9PrcjWfsOrwKE21mhmD8/uPx73xrmKQe92jGIRr0Ks=,iv:p6tuqDMxKtXNJ0tDyqrD4N+tLBIkJJmFqQzeZGLUUqE=,tag:lTGmnNdr1Tbe31iOs3fpWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q5n697fssrl29mq4c0zkq6h2s6c7gua7cghtu68ezqlm8vuauchq2hd59t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOXFPelJvdWhRcTg0cWN5
            ZnRNZVEvU3p0VEl4a3hzMXpJY251RGFaYnhBCmo0NW9aSk51RUFJVE83eVFBVHVD
            L1A3NzdDYmNHQVBXUlNDU1FJY2NaTTQKLS0tIDYxYkgvZmZjS2xCcUo3UXIwWGVZ
            SGFYMEJIcDdzU2NpdzBYWXg3Wm9SUDgKfoH2XbSA/h/ATB4s+jSfwzq2tqZh2/1J
            N/NBVjf6r58h/FQx81IAsyzgwO+N1i1t90GeRUSIdUkAJ8aBirqaVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T15:16:14Z"
    mac: ENC[AES256_GCM,data:StRLU8Gu2xP/dEE5KyHL/JGr0DNT7epK7SdNyEiMo9XzvgR14A1/XrbIGD9QHWuMDOAaltelTfCUO6sPeUxIs2A6jhG4D2ACCC0EHpLAnvo31jMxL80zJYyBP7SAffL/rAQGq0hFIHdUEyXJx6uPZtmCUu9RELjdCrdiHspd/oo=,iv:z1epMZMGBPjYKXANEU/0yJTg7ehbtSic7L+7Gsxi0h0=,tag:sr24ut0jeqjgkoYrG4iXbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
